name: flutter_clip
description: Calculator Language for Immediate Processing
version: 1.0.5
homepage: http://www5d.biglobe.ne.jp/~satis/

environment:

  sdk: ">=2.17.1 <3.0.0"

  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter

  dart_clip: ^1.0.5

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
