name: flutter_clip
description: Calculator Language for Immediate Processing
version: 1.0.0

environment:

  sdk: ">=2.17.1 <3.0.0"

  flutter: ">=1.17.0"

dependencies:

  flutter:
    sdk: flutter

  clip:
    path: ../clip/

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
